### ISSUE TITLE
Problems when uploading to heroku

### ISSUE THREAD

**Issue by charlotron** [coveo-labs/slack-bot#1]
Hi, 

Seems a wonderful project this one! 

Unfortunately I am having troubles while executing it, maybe some python version problem?

 Once uploaded the python code and executed in the heroku cli:

>heroku logs --tail

I can see there are some syntax issues with the "print" command from python, It is asking for some paranthesis. After adding them it seems fixed but a new bug appeared. As long as I am not mastered in Python (maybe different python versions?), I cannot solve all the bugs.

Have you faced this problem? Maybe Heroku upgraded its Python version or something like?

Regards!

**Comment by charlotron** [comment]
Thank you adding the following file solved to me, you should consider adding the trunk master
[runtime.txt](https://github.com/coveo-labs/slack-bot/files/1979460/runtime.txt)

**Comment by jdevost** [comment]
You're right. Thanks for the suggestion. Done.
